# -*- coding: utf-8 -*-
"""churn_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRtjBA6nxH9yo106os13rHp_sH0cBZMl
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/churn_analysis.csv")
df.head()

print(df.shape)
print(df['Exited'].value_counts(normalize=True).round(3))

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

features = ['CreditScore', 'Age', 'Tenure', 'Balance',
            'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']

X = df[features]
y = df['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print(classification_report(y_test, model.predict(X_test)))

importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)

print(importance_df)
importance_df.to_csv("feature_importance.csv", index=False)

df['churn_probability'] = model.predict_proba(X)[:, 1]
high_risk = df[df['churn_probability'] > 0.7][['CustomerId', 'Geography', 'Age', 'Balance', 'churn_probability']]
high_risk.to_csv("high_risk_customers.csv", index=False)
print(f"{len(high_risk)} high-risk customers identified")

# Add Geography and Gender for Power BI segmentation
df['churn_probability'] = model.predict_proba(X)[:, 1]
high_risk = df[df['churn_probability'] > 0.7][[
    'CustomerId', 'Geography', 'Age', 'Gender',
    'Balance', 'NumOfProducts', 'IsActiveMember', 'churn_probability'
]]
high_risk.to_csv("high_risk_customers.csv", index=False)
print(f"{len(high_risk)} high-risk customers exported")

# Export full dataset with churn probability for Power BI
df.to_csv("bank_churn_scored.csv", index=False)
print("Full scored dataset exported")

